version: '3.8'
services:
    #Zookeeper (Kafka için)
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
    
    #Kafka
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on: [zookeeper]
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
    
    # Redis
    redis:
        image: redis:7-alpine
        ports:
        - "6379:6379"
        command: ["redis-server", "--save", "", "--appendonly", "no"]

    # MongoDB
    mongo:
        image: mongo:6
        ports:
        - "27017:27017"

    # networks:
    #     default:
    #         driver: bridge